version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    networks:
      - atvcloudfinal
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: atvcloudfinal
      MYSQL_USER: root
      MYSQL_PASSWORD: user
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql/scripts:/docker-entrypoint-initdb.d
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  nodejs:
    build: 
      context: .
    image: alexandrefernandez88/atvcloudfinal:0.0.6
    restart: always
    container_name: nodejs
    networks:
      - atvcloudfinal
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - mysql

networks:
  atvcloudfinal: