version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: atvcloudfinal
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql/scripts:/docker-entrypoint-initdb.d
      - ./mysql_data:/var/lib/mysql
      - .:/docker-entrypoint-initdb.d/:rw
    networks:
      - atvcloudfinal

  nodejs:
    build:
      context: .
      dockerfile: dockerfile
    container_name: nodejs
    image: alexandrefernandez88/atvcloudfinal:0.0.4
    restart: always
    networks:
      - atvcloudfinal
    tty: true
    depends_on:
      - mysql
    ports:
      - "3000:3000"

networks:
  atvcloudfinal