version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    networks:
      - atvcloudfinal
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: atvcloudfinal
      MYSQL_USER: user
      MYSQL_PASSWORD: passwd
    volumes:
      - .:/docker-entrypoint-initdb.d/:rw
    ports:
      - 3306:3306



  index:
    # build: .
    image: alexandrefernandez88/atvcloudfinal:0.0.2
    container_name: nodejs
    restart: always
    ports:
      - 3000:3000
    networks:
      - atvcloudfinal
    depends_on:
      - mysql

networks:
  atvcloudfinal: